version: '3.7'

services:
  app1:
    build: app1
    ports:
      - 5001:5000
  app2:
    build: app2
    ports:
      - 5002:5000
  nginx:
    container_name: nginx
    build: nginx
    # bind the port 80 of container to machine port 9090
    ports:
      - 9090:80
    # make app as nginx dependency service
    depends_on:
      - app1
      - app2
  