name:  Build and push docker image on commit

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps: 
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Auto tagging of releases
      id: extract_sha
      run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      
    - name: Check outputs
      env:
        SHORT_SHA: ${{steps.extract_sha.outputs.SHORT_SHA}}
      run: |
        echo "Commit SHA: $SHORT_SHA"
      
    - name: Configure AWS creds
      uses: aws-actions/configure-aws-credentials@v4
      with:
        output-credentials: true
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: il-central-1
        
    - name: Login to Amazon ECR
      id: login-ecr
      uses: docker/login-action@v3
      with:
        registry: 098945065860.dkr.ecr.il-central-1.amazonaws.com
      #uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: 098945065860.dkr.ecr.il-central-1.amazonaws.com
        ECR_REPOSITORY: my_repo
        IMAGE_TAG: "${{ steps.extract_sha.outputs.short_sha }}"
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        echo "{image} = {$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG}"
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG        


    
    #- name: Set outputs 
    #  id: vars
    #  run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    #- name: Build the Docker image
      
    #run: docker build . --file Dockerfile --tag my-image-name:${{ steps.vars.outputs.sha_short }}
